title:              Etienne & His Rabbit Holes
email:              post-lefebvre@riseup.net
description:        My thoughts on the meta-crisis and all things related to our global predicament
author:             Etienne-Lefebvre
baseurl:            ""
url:                "https://Etienne-Lefebvre.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
permalink:          /:name/ 
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
